#!/usr/bin/python

# http://rosalind.info/problems/ba9k/?class=437

str = "CAGCTCGCGGGAACGCTAGGACTTAACAACAGTGGACCAACGCAGGTCGTTTCCATTATGCAATCAATTCTTGCCAAGCGGTTACGTTCAAGATTTGAGTCCGCGCATTAATATTGATTATTGGATTTAACGCTAAAGTCCCATCGTTCATGCGTACCTCTCGCTAAAGGTTGGTAGGGATATACTGTTGATTGGAACGGACCCAGATGGAACTCTCGCTCACCTGTCTCCGCGCCACCCCAGTCGTACATACAAGGCTGATTGCAAGGGGCTTTTAAGGAAAGGGTGCAATAAGGACGACTCTGTTCCACATTATAGGCTTCCGTACGCTTGGCTTCTTACTATCGCCAGCGTCCTATTCATGGGAGCTGCTTAGTGGCGTAGAAGCCAGCGCGGGCAGCAATAGTTCGCTTTTTTTATCTCAGTCATTCAATACCCAGTTTCCTAGATTCGCAGGCACGACTCCCAACTCGCCGTCGAGGTCGATTTTTGTGTAACCGATTTTATGAAGGTTCGCGTGCACAAATTGCAGGGGCTAAAAGTTTCTTGTTGCACATCTGCCATAATGCGCTCAGTTCCGTTCTTTACTTCGACGTAAAGAGCTTGAGATTGGCACAGAGAGTGAGCACGCAAGAATATGTGAAATAAATTCCGCTTCGGCTGCCTTCCTTCCCTGGTGTGTGCTGTCAGATTATCGGGGAGCGGGAGTTCTGAAAAAGTTCGGCCGGATTAAACCATCACGCGCCGACCAAGTGTACTCGAACAGGGTGTTATATAAATATACGGTTGCCTCAATCTAGGAGCATCCAGACCTCGGCTGGGGGGTGAAGAGTCGCATCCACAGAGACAGGACAACCCAGGTCTTAGCAATGGGACTACCCGGCTATACGAAAGAGCTTGAAATTTAACCTGATAAGGGAATGAAAA$"
pl = 170

freq = {
    'A': 0,
    'C': 0,
    'T': 0,
    'G': 0
}

for i in str:
    if i != '$':
        freq[i] += 1

c = str[pl]
count_before = 0

for i in range(0, pl):
    if str[i] == c:
        count_before += 1

pos = 1

for key, val in freq.iteritems():
    if key < c:
        pos += val

pos += count_before

print pos