#!/usr/bin/python

# http://rosalind.info/problems/ctea/?class=437

str1 = "NMVVHACDCPAYKRMSKVHDPIEYKCKKKNRVTVNPLSMAALFQNWETRIARKWSPVAHNYTCLRFGVLWCMIGPMCLGQAQFPNARIFLSSTLDMSVLLFVVNPKYVTPLLVDAIGHCYLCCHGPRWHWNQAEFVGSCRVVVGNMGTKWAENYESEGCTNQYMDHATMISFQQDLDLMFGQDLNSHWHQPKGLQEAGLASEFCSPFKYDQREYCIRNNLCTRMGHGDVRWPKKFGFPHMVKQWQWPNDSHSHPQLKQVAPPAKRQSIDAAVSDCCLPSFDIGVDDKMKFMYTTHVEGAFQHIHSAIFLYVAVDCRHGCRTDYRTNHETWYGPPQQNCCHDSKSYKCIPWVIFVRHSPCNAQGHIMRWYKLSWWEKWIPRLQQNRNTEYNDSKAGGSIQMAFCKREWFVFNKWNLTVLEEEMKCAGNCFECHDTKEKEVCFFYELMESLGTSGIHCIFNNVPYIQMWMADFAVNKKMCIPQMDGFCKVCDMNRTQCGHFGGTTCNERLNSHETNQARKNRNEKEFACHRMFIVQWYFPNGRYRYQMFVFMLQHSYNDNDLPNRKNQLGFNFVWSKKLDCCIFKAFVSPGKWCHGDFPIGLRFWRIQCERNGIHFHTTMLYGRWFPYEHNSHKQCNAQRTSIYRMAWNCYQKNSMMWMHWLGGFIYERSTAHCFKQQHHFCLWGAGCTVNPHEETQQYPFFPVCIMDPWDVWHIYTTNFKYPGKHHRRVPDERMAIQLWCVTALTKNGEPRFFSFITTYKSCQLKPLCIHCMWAPTEDEYMSGPCYLSQAYIHWSHTQCTWICTRLWCTSCWNPPWLKYTKVTIYTEENARPGTYKVGISRPMEDTQDNFDI"
str2 = "NMKSHACDCPAYKRQSCVHMMTGYQEHDPIEYKCKKKNRVYTWQTVNNEMLYLIKICSKALFQNWETEFHVLQCMIGPMCLGDAQFPNKRIFLWSTLDMSVLLFVCCTFQWNTCCIGGKYVIGHPYLCCHGPRWHSNQPISWVGNMYESEGCTNQYMDDTEITHRATMISFQQILDYMFQPDLNSHWTDALCLVGLASEFCGPFKYNWKQYCLPVQREYCIRNNLIVHVKGVDGFSPECSRMGHGDVRWPKKFGLPHMNKQWQWPNTSHSHPQVKQVAPIIDAADCCLPSFDWGADDVEGAFQHIHSAIFLYVAVVCRHGCTDYRTPHHETWNGINLIETEPQQMDINSFVSVDSYDLIYKCIPYVISPCNAQGHIMLWYKLSWWSSKWMPAKGQNRWTEATDSKAGGSIQMAFCKREWKHAVFNAQCKLWVLTVLEEEMKCAGNCFPRFRNVCCHDVKEKPVCVLMESLGTPGIHCIFNNFGIGEFQHNYIFAVNKKMCIPQMDGFEKVCDMNRTQVLFEGHFGGTTCNERLNAHETNQARSNRNEKEFACHFGVLMQRWIVQFLMNLGIPEYFPNIRLHCYTYWHVFMLQHSYNDNDLPNRKAGSMHQFQAGFNFVWTKKAQCCKWCHGDFPIGLKCERNGIHFHDEMVLHSTMQCNAQRTSHIWGNFLLQHFQGGFNVHCPMQGPCDHHFCLWGAGCTSPNMTVPHEFARIMDPWWANQKFVWHQRTEDPCTAMGHTTKFKYPVNDERMMIQLWCVTAPRSMQLKHCMWGPTEDEYMTAWRLFGHCSATQCTWICTRLWCTSCTKYLMDTINTEENARPGTYKVGISPTPKASHPMESTQDNFDI"

dp = [[0] * (len(str2)+1) for _ in range(len(str1)+1)]
cnt = [[0] * (len(str2)+1) for _ in range(len(str1)+1)]
#print dp
for i in range(0, len(str1)+1):
    dp[i][0] = i
    cnt[i][0] = 1
for j in range(1, len(str2)+1):
    dp[0][j] = j
    cnt[0][j] = 1

#print dp
#print cnt
#print len(dp)
#print len(dp[0])

for i in range(1, len(str1)+1):
    for j in range(1, len(str2)+1):
        #print i,j
        x = (str1[i-1] != str2[j-1])
        a = 1+dp[i-1][j]
        b = 1+dp[i][j-1]
        c = x+dp[i-1][j-1]
        if a == min(a,b,c):
            cnt[i][j] += cnt[i-1][j]
        if b == min(a,b,c):
            cnt[i][j] += cnt[i][j-1]
        if c == min(a,b,c):
            cnt[i][j] += cnt[i-1][j-1]
        dp[i][j] = min(1+dp[i-1][j], 1+dp[i][j-1], x+dp[i-1][j-1])

        cnt[i][j] = cnt[i][j] % 134217727

print cnt[len(str1)][len(str2)]
